
name: build-angle-x86

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: build
        id: build
        shell: cmd
        run: call build.cmd --x86

      - name: release
        id: release
        if: steps.build.outputs.ANGLE_COMMIT != ''
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.build.outputs.BUILD_DATE }}
          release_name: ${{ steps.build.outputs.BUILD_DATE }}
          body: |
            [angle commit](https://github.com/google/angle/commit/${{ steps.build.outputs.ANGLE_COMMIT }})
        continue-on-error: true

      - name: upload
        id: upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: "angle-x86-${{ steps.build.outputs.BUILD_DATE }}.zip"
          asset_name: "angle-x86-${{ steps.build.outputs.BUILD_DATE }}.zip"
          asset_content_type: application/zip
