
name: build-angle

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: build-x86
        id: build-x86
        shell: cmd
        run: call build.cmd x86

      # - name: build-x64
      #   id: build-x64
      #   shell: cmd
      #   run: call build.cmd x64

      - name: release
        id: release
        if: steps.build.outputs.ANGLE_COMMIT != ''
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.build.outputs.BUILD_DATE }}
          release_name: ${{ steps.build.outputs.BUILD_DATE }}
          body: |
            [angle commit](https://github.com/google/angle/commit/${{ steps.build.outputs.ANGLE_COMMIT }})

      - name: upload-x86
        id: upload-x86
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: "angle-x86-${{ steps.build.outputs.BUILD_DATE }}.zip"
          asset_name: "angle-x86-${{ steps.build.outputs.BUILD_DATE }}.zip"
          asset_content_type: application/zip

      # - name: upload-x64
      #   id: upload-x64
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.release.outputs.upload_url }}
      #     asset_path: "angle-x64-${{ steps.build.outputs.BUILD_DATE }}.zip"
      #     asset_name: "angle-x64-${{ steps.build.outputs.BUILD_DATE }}.zip"
      #     asset_content_type: application/zip
